# Generated by Django 4.1.2 on 2022-10-29 13:23

from django.db import migrations, models
import django.db.models.deletion
import shop.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, validators=[shop.models.validation_html])),
                ('name', models.CharField(max_length=50, validators=[shop.models.validation_html])),
                ('description', models.CharField(max_length=100, validators=[shop.models.validation_html])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('deleted_at', models.DateField(auto_now_add=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, validators=[shop.models.validation_html])),
                ('name', models.CharField(max_length=50, validators=[shop.models.validation_html])),
                ('descriptions', models.CharField(default='write description', max_length=100, validators=[shop.models.validation_html])),
                ('limited', models.BooleanField(default=False, validators=[shop.models.validation_html])),
                ('sales_price', models.IntegerField(validators=[shop.models.validation_html])),
                ('regular_price', models.IntegerField(validators=[shop.models.validation_html])),
                ('available_colors', models.CharField(max_length=100, validators=[shop.models.validation_html])),
                ('image', models.ImageField(upload_to='upload/image')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('deleted_at', models.DateField(auto_now_add=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
