# Generated by Django 4.1.2 on 2022-10-29 13:45

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[shop.models.validation_html]),
        ),
    ]
