# Generated by Django 4.1.2 on 2022-10-30 15:18

from django.db import migrations, models
import shop.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, validators=[shop.models.validation_html])),
                ('varients_name', models.CharField(max_length=100)),
            ],
        ),
    ]
