# Generated by Django 4.1.2 on 2022-10-30 16:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_varients'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_value', models.JSONField()),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.varients')),
            ],
        ),
    ]
