# Generated by Django 4.1.2 on 2022-10-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_type',
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_name',
            field=models.CharField(choices=[('size', 'size'), ('Colors', 'Colors')], default='size', max_length=10),
        ),
    ]
