# Generated by Django 4.1.2 on 2022-10-31 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_attribute_attribute_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_name',
        ),
    ]
