# Generated by Django 4.1.2 on 2022-10-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_attribute_attribute_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_name',
        ),
    ]
