# Generated by Django 4.1.2 on 2022-10-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_attribute_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attribute_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.varients'),
        ),
    ]
