# Generated by Django 4.1.2 on 2022-10-31 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_attribute_attribute_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='colour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='attribute',
        ),
    ]
