# Generated by Django 4.1.2 on 2022-10-31 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_colour_size_delete_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
