# Generated by Django 4.1.2 on 2022-10-31 12:49

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.CharField(max_length=100, validators=[shop.models.validation_html]),
        ),
    ]
