# Generated by Django 4.1.2 on 2022-10-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_produt_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produt_item',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
