# Generated by Django 4.1.3 on 2022-11-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_shopping_cart_shopping_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
