# Generated by Django 4.1.3 on 2022-11-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_user_id_shopping_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopping_cart_item',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='shopping_cart_item',
            old_name='product_item_id',
            new_name='product_item',
        ),
    ]
