# Generated by Django 4.1.3 on 2022-11-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rename_cart_id_shopping_cart_item_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produt_item',
            name='stock',
        ),
    ]
