# Generated by Django 4.1.3 on 2022-11-26 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0021_remove_produt_item_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Whishlist_item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produt_item')),
                ('whishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.whishlist')),
            ],
        ),
    ]
