# Generated by Django 4.1.3 on 2022-11-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0001_initial'),
        ('shop', '0022_whishlist_whishlist_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produt_item',
            new_name='Product_item',
        ),
    ]
