# Generated by Django 4.1.3 on 2022-11-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_rename_produt_item_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart_item',
            name='cart',
        ),
    ]
