# Generated by Django 4.1.3 on 2022-11-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_shopping_cart_item_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart_item',
            name='product_item',
        ),
        migrations.RemoveField(
            model_name='whishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='whishlist_item',
            name='product_item',
        ),
        migrations.RemoveField(
            model_name='whishlist_item',
            name='whishlist',
        ),
        migrations.DeleteModel(
            name='shopping_cart',
        ),
        migrations.DeleteModel(
            name='shopping_cart_item',
        ),
        migrations.DeleteModel(
            name='Whishlist',
        ),
        migrations.DeleteModel(
            name='Whishlist_item',
        ),
    ]
