# Generated by Django 4.1.3 on 2022-11-30 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_product_item_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='attribute_option',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='product_attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attribute_option')),
                ('productItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product_item')),
            ],
        ),
        migrations.RemoveField(
            model_name='variation_option',
            name='variation',
        ),
        migrations.DeleteModel(
            name='product_item_configuration',
        ),
        migrations.DeleteModel(
            name='variation',
        ),
        migrations.DeleteModel(
            name='variation_option',
        ),
    ]
