# Generated by Django 4.1.3 on 2022-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_delete_varients_remove_product_item_colour_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute_option',
            name='attribute',
        ),
        migrations.AddField(
            model_name='attribute_option',
            name='attribute',
            field=models.ManyToManyField(to='shop.attribute'),
        ),
    ]
