# Generated by Django 4.1.3 on 2022-11-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_remove_attribute_option_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_option',
            name='attribute_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.attribute'),
        ),
    ]
