# Generated by Django 4.1.3 on 2022-11-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_attribute_option_attribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute_option',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='product_attribute',
            name='attribute_option',
        ),
        migrations.RemoveField(
            model_name='product_attribute',
            name='productItem',
        ),
        migrations.DeleteModel(
            name='attribute',
        ),
        migrations.DeleteModel(
            name='attribute_option',
        ),
        migrations.DeleteModel(
            name='product_attribute',
        ),
    ]
