# Generated by Django 4.1.3 on 2022-11-30 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_attribute_option_attribute_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=50)),
                ('attribute_value', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product_attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.attribute')),
                ('productItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product_item')),
            ],
        ),
    ]
