# Generated by Django 4.1.2 on 2022-11-03 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
                ('address_line', models.CharField(max_length=50)),
                ('address_line2', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
