# Generated by Django 4.1.2 on 2022-11-03 08:42

import Address.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='address',
            name='State',
            field=models.CharField(max_length=50, validators=[Address.models.CheckIstext, Address.models.LimitedValue]),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=50, validators=[Address.models.LimitedValue]),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(max_length=50, validators=[Address.models.LimitedValue]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, validators=[Address.models.CheckIstext, Address.models.LimitedValue]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_name',
            field=models.CharField(max_length=50, validators=[Address.models.CheckIstext, Address.models.LimitedValue]),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[Address.models.IsVlaidPostCode]),
        ),
    ]
