# Generated by Django 4.1.3 on 2022-11-28 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_shopping_cart_item_product_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWhishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhishlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product_item')),
                ('whishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.userwhishlist')),
            ],
        ),
    ]
