# Generated by Django 4.1.3 on 2022-11-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_userwhishlist_whishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlistitem',
            name='productItem',
        ),
        migrations.RemoveField(
            model_name='whishlistitem',
            name='whishlist',
        ),
        migrations.DeleteModel(
            name='UserWhishlist',
        ),
        migrations.DeleteModel(
            name='WhishlistItem',
        ),
    ]
