# Generated by Django 4.1.3 on 2022-11-21 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0021_remove_produt_item_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField()),
                ('productItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produt_item')),
            ],
        ),
    ]
